### ISSUE TITLE
How to flip Video horizontally and vertically

### ISSUE THREAD

**Issue by gannaramu** [arkhipenko/esp32-mjpeg-multiclient-espcam-drivers#1]

**Comment by leogala** [comment]
I had the same doubt. 
I solved by adding in setup() after the camera initialization, before "IPAddress ip":

  static sensor_t * s = esp_camera_sensor_get();
  //set initial flips
  s->set_hmirror(s, 1);
  s->set_vflip(s, 1);
  
BTW, Excellent work !

**Comment by arkhipenko** [comment]
Looks like you have found the solution. Thanks!
