### ISSUE TITLE
Vertical Flip

### ISSUE THREAD

**Issue by jimthedj65** [arkhipenko/esp32-mjpeg-multiclient-espcam-drivers#10]
Firstly, thanks for the code, it runs on my two ESP-EYE with a slight delay, I think its my wifi as depending on what ip address it gets depends on the latency, no idea nor can I make sense of it, but all works great.

If I wanted to flip the video back the other way, where would I modify it prior to compiling? I did try to modify m99141_regs.h at  line #define TIMING_TC_REG20_VFLIP   0x00 /* Vertical flip enable */ I tried a few settings to no avail.

thanks

**Comment by arkhipenko** [comment]
sensor_t* s = esp_camera_sensor_get();
  s->set_vflip(s, true);   // or false
