### ISSUE TITLE
use git submodule for including upstream https://github.com/espressif/esp32-camera.git drivers

### ISSUE THREAD

**Issue by ericfont** [arkhipenko/esp32-mjpeg-multiclient-espcam-drivers#18]
I like your project, though I have to admit the installation procedue was a little bit unusual and error prone.  And if I want to update to new drivers, then I have to look closely at those steps again.  I believe the proper way to include other projects with git is to use git submodules.  And keep those other projects in a separate folder.  That makes it easy to install and update to newer drivers, and also makes it clear what files belong to this git project and which files belong to upstream developers.

**Comment by arkhipenko** [comment]
Hi there. This whole "procedure" that I concocted is just a dirty hack, not a proper way to include a submodule. It will have to potentially change every time Espressif changes something in there code.
If you figure out a way how to compile Espressif's stuff as a subfolder - please DO let me know!
