### ISSUE TITLE
Feature request: PIO + EmbUI + ESPAsyncWebServer support/example

### ISSUE THREAD

**Issue by DmytroKorniienko** [arkhipenko/esp32-mjpeg-multiclient-espcam-drivers#3]
Hi. How are you? Hope you doing well.

I started new fork which based on your repo and want to mix out EmbUI framework with esp32-mjpeg-multiclient code. I prefered working in the VS-Code + PIO, so had migrated your code into it. In addition EmbUI using ESPAsyncWebServer instead Webserver, so I changed some calls as well. Now all partially worked, but unfortuanetelly I have broking output only small part of buffer. Can you look at code or provide an example for ESPAsyncWebServer?

And many thanks for your work!

![FrameBuffer](https://user-images.githubusercontent.com/26786760/97460930-e3c97280-1945-11eb-8eaf-e8c7fdd811b2.JPG)

**Comment by arkhipenko** [comment]
Which of the 3 flavors are you using?

**Comment by DmytroKorniienko** [comment]
> Which of the 3 flavors are you using?
\esp32-mjpeg-multiclient-espcam-drivers\version\esp32-cam-rtos-allframes\esp32-cam-rtos-allframes
* issue only for ESPAsyncWebServer, ordinary web server worked as expected

**Comment by DmytroKorniienko** [comment]
Nevermind. I found an example: https://gist.github.com/me-no-dev/d34fba51a8f059ac559bf62002e61aa3 :)
