### ISSUE TITLE
White LED pulsing in CAMERA_MODEL_AI_THINKER 

### ISSUE THREAD

**Issue by charliejgallo** [arkhipenko/esp32-mjpeg-multiclient-espcam-drivers#8]
When using the Ai Thinker module the "Flash" Led was pulsing during use (maybe due to bad pulldown resistors in my board or  the base of the transistor driving the white LED, IDK) ....

pulsing and blinking stopped when adding:

`#if defined(CAMERA_MODEL_AI_THINKER)
  pinMode(4, OUTPUT);  //Led Flash in  gpio4
  digitalWrite(4, LOW);
#endif
`
in void Setup()

**Comment by arkhipenko** [comment]
Sorry - I have not experienced this issue with multiple AI THinker models I used.
I do not believe there is even code that drives the flash pin.
